apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: demo
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: demo
  minReplicas: 2
  maxReplicas: 20
  targetCPUUtilizationPercentage: 50
